version: '2'
services:
    nginx:
        image: nginx:1.23
        ports:
          - "80:80"
        restart: on-failure
        volumes:
            - ./docker-images/nginx-extended/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/code
        links:
          - php-fpm-parser
        depends_on:
          - php-fpm-parser
        networks:
          default:
            aliases:
                - parser
    php-fpm-parser:
        build: ./docker-images/php-extended
        restart: on-failure
        container_name: php-fpm-parser
        ports:
            - '8080:8080'
        expose:
            - 8080
        environment:
          - PHP_IDE_CONFIG=serverName=parser
        volumes:
            - ./:/code:cached
            - ./docker-images/php-extended/php.ini:/usr/local/etc/php/conf.d/custom.ini
        working_dir: /code
        tty: true
        links:
          - redis
        depends_on:
          - redis
    redis:
      image: 'redis'
      ports:
        - '6379:6379'
      volumes:
        - ./data/redis:/data
